sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-local
    - python: 2.7
      env: TOXENV=py27-integ
    - python: 2.7
      env: TOXENV=py27-accept
    - python: 2.7
      env: TOXENV=py27-examples
    - python: 3.4
      env: TOXENV=py34-local
    - python: 3.4
      env: TOXENV=py34-integ
    - python: 3.4
      env: TOXENV=py34-accept
    - python: 3.4
      env: TOXENV=py34-examples
    - python: 3.5
      env: TOXENV=py35-local
    - python: 3.5
      env: TOXENV=py35-integ
    - python: 3.5
      env: TOXENV=py35-accept
    - python: 3.5
      env: TOXENV=py35-examples
    - python: 3.6
      env: TOXENV=py36-local
    - python: 3.6
      env: TOXENV=py36-integ
    - python: 3.6
      env: TOXENV=py36-accept
    - python: 3.6
      env: TOXENV=py36-examples
# disabling Bandit run in Travis pending resolution of https://bugs.launchpad.net/bandit/+bug/1749603
#    - python: 3.6
#      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=readme
# pending reorg of deserialize_header
#    - python: 3.6
#      env: TOXENV=flake8
#    - python: 3.6
#      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=flake8-tests
    - python: 3.6
      env: TOXENV=pylint-tests
    - python: 3.6
      env: TOXENV=flake8-examples
    - python: 3.6
      env: TOXENV=pylint-examples
install: pip install tox
script: tox
