sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=readme
install: pip install tox-travis
script: tox