sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=readme
# pending reorg of deserialize_header
#    - python: 3.6
#      env: TOXENV=flake8
#    - python: 3.6
#      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=flake8-tests
    - python: 3.6
      env: TOXENV=pylint-tests
    - python: 3.6
      env: TOXENV=examples
    - python: 3.6
      env: TOXENV=flake8-examples
    - python: 3.6
      env: TOXENV=pylint-examples
install: pip install tox
script: tox
